apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
  labels:
    app: k8s-simple-deploy
    type: simple-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      project: slb
  template:
    metadata:
      labels:
        project: slb
    spec:
      containers:
        - name: slb-web
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  labels:
    env: prodoction
spec:
  type: LoadBalancer
  selector:
    project: slb # pod selector by labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 4000 # port on lb
      targetPort: 80 # port on pod
