apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-deploy
  labels:
    app: k8s-multi-deploy
    type: multi-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      project: mlb
  template:
    metadata:
      labels:
        project: mlb
    spec:
      containers:
        - name: mlb-web
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80
        - name: mlb-api
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: multi-service
  labels:
    env: production
spec:
  type: LoadBalancer
  selector:
    project: mlb # pod selector by labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 3000 # port on lb
      targetPort: 80 # port on pod
    - name: api-listener
      protocol: TCP
      port: 4000 # port on lb
      targetPort: 8080 # port on pod
