apiVersion: v1
kind: Pod
metadata:
  name: nginx-v2
  labels:
    env: production
    app: main
spec:
  containers:
    - name: container-apache
      image: nginx:latest
      ports:
        - containerPort: 80
